Bill.Web.UI/Controllers/InvoicesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Bill.DAL;
using Bill.DAL.DataAccesses;
using Bill.DataModels;
using Bill.BLL;
using Bill.Web.UI.ViewModels;

namespace Bill.Web.UI.Controllers
{
    public class InvoicesController : Controller
    {
        private readonly InvoiceLogic invoiceLogic = new InvoiceLogic();
        private readonly InvoiceDataAccess invoiceDA = new InvoiceDataAccess(); 
        private readonly ClientDataAccess clientDA = new ClientDataAccess();
        private readonly CompanyDataAccess companyDA = new CompanyDataAccess();

        public async Task<ActionResult> Index(string sortOrder, string searchString)
        {
            ViewBag.CurrentSort = sortOrder;
            ViewBag.DateSortParam = String.IsNullOrEmpty(sortOrder) ? "date_desc" : "";
            ViewBag.EmailSortParam = sortOrder == "email" ? "email_desc" : "email";
            ViewBag.CompanySortParam = sortOrder == "company" ? "company_desc" : "company";
            ViewBag.FinishedSortParam = sortOrder == "finished" ? "finished_desc" : "finished";
            ViewBag.CurrentFilter = searchString;

            List<Invoice> invoices = await invoiceDA.GetInvoices();
            invoices = invoiceLogic.GetActiveInvoices(invoices);
            invoices = invoiceLogic.SortTable(sortOrder, invoices);

            if (!string.IsNullOrEmpty(searchString))
            {
                invoices = invoiceLogic.SearchInvoices(searchString, invoices);
            }
            return View(invoices);
        }

        public async Task<ActionResult> Details(int id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Invoice invoice = await invoiceDA.GetInvoice(id);
            invoice.TotalBeforeVAT = invoiceLogic.CalculateTotalBeforeVAT(invoice);
            invoice.TotalPerVATRate = invoiceLogic.CalculateTotalPerVATRate(invoice);
            invoice.TotalAfterVAT = invoiceLogic.CalculateTotalAfterVAT(invoice.TotalPerVATRate);
            if (invoice == null)
            {
                return HttpNotFound();
            }
            return View(invoice);
        }

        public async Task<ActionResult> Create()
        {
            Invoice invoice = new Invoice();
            List<Client> clients = await clientDA.GetClients();
            List<Company> companies = await companyDA.GetCompanies();
            return View(new InvoiceClientsCompanies() { Invoice = invoice, Clients = clients, Companies = companies });
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include = "ID,Date,Finished,Deleted,ClientID,CompanyID")] Invoice invoice)
        {
            if (ModelState.IsValid)
            {
                await invoiceDA.CreateInvoice(invoice);
                return RedirectToAction("Index");
            }

            return View(invoice);
        }

        public async Task<ActionResult> Edit(int id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Invoice invoice = await invoiceDA.GetInvoice(id);
            List<Client> clients = await clientDA.GetClients();
            List<Company> companies = await companyDA.GetCompanies();
            if (invoice == null)
            {
                return HttpNotFound();
            }
            return View(new InvoiceClientsCompanies() { Invoice = invoice, Clients = clients, Companies = companies } );
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "ID,Date,ClientID,CompanyID")] Invoice invoice)
        {
            if (ModelState.IsValid)
            {
                await invoiceDA.EditInvoice(invoice);
                return RedirectToAction("Index");
            }
            return View(invoice);
        }

        public async Task<ActionResult> Delete(int id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Invoice invoice = await invoiceDA.GetInvoice(id);
            if (invoice == null)
            {
                return HttpNotFound();
            }
            return View(invoice);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id, string deleteMessage)
        {

            await invoiceDA.DeleteInvoice(id, deleteMessage);
            return RedirectToAction("Index");
        }
    }
}

Bill.Web.UI/Views/Invoices/Create.cshtml
@model Bill.Web.UI.ViewModels.InvoiceClientsCompanies

@{
  ViewBag.Title = "Factuur maken";
}

<h2>Maak een nieuwe Factuur</h2>


@using (Html.BeginForm())
{
  @Html.AntiForgeryToken()
  <div class="form-horizontal">
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
      @Html.LabelFor(model => model.Invoice.Date, htmlAttributes: new { @class = "control-label col-md-2" })
      <div class="col-md-6">
        @Html.EditorFor(model => model.Invoice.Date, new { htmlAttributes = new { @class = "form-control" } })
        @Html.ValidationMessageFor(model => model.Invoice.Date, "", new { @class = "text-danger" })
      </div>
    </div>

    <div class="form-group">
      <div class="col-md-6">
        @Html.DropDownListFor(m => m.Invoice.ClientID, new SelectList(Model.Clients, "ID", "Email"), "Selecteer klant", new { @class = "form-control" })
      </div>
    </div>

    <div class="form-group">
      <div class="col-md-6">
        @Html.DropDownListFor(m => m.Invoice.CompanyID, new SelectList(Model.Companies, "ID", "Name"), "Selecteer bedrijf", new { @class = "form-control" })
      </div>
    </div>

    <div class="form-group">
      <div class="col-md-offset-2 col-md-10">
        <a href="/invoices" class="btn btn-light">Terug</a>
        <input type="submit" value="Create" class="btn btn-primary" />
      </div>
    </div>
  </div>
}

@section Scripts {
  @Scripts.Render("~/bundles/jqueryval")
}

Bill.Web.UI/Views/Invoices/Delete.cshtml
@model Bill.DataModels.Invoice

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Invoice</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Date)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Date)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Finished)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Finished)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Deleted)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Deleted)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ClientID)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ClientID)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CompanyID)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CompanyID)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Bill.Web.UI/Views/Invoices/Details.cshtml
@model Bill.DataModels.Invoice

@{
  ViewBag.Title = $"Details {Model.FormattedCode}";
}

<div class="row my-4">
  <h2 class="">Factuur @Model.FormattedCode</h2>
  @if (Model.Finished)
  {
    <span class="badge badge-success my-auto ml-2 p-2 d-print-none">Afgewerkt</span>
  }
  <div class="ml-auto my-auto d-print-none">
    <button class="btn btn-light mr-2" onclick="window.print()"><i class="fas fa-print"></i>&nbsp;Adrukken</button>
    <button class="btn btn-danger mr-2" data-toggle="modal" data-target="#deleteModel"><i class="fas fa-trash"></i>&nbsp;Verwijderen</button>
    <button class="btn btn-primary @(@Model.Finished ? "disabled" : "")"><i class="fas fa-plus"></i>&nbsp;Item toevoegen</button>
  </div>
</div>


<div class="row mb-4 h-100">
  <div class="col-5">
    <div class="card p-4">
      <h2>@Html.DisplayFor(i => i.Company.Name)</h2>
      <p class="m-0">@Html.DisplayFor(i => i.Company.Street)</p>
      <p class="m-0">@Html.DisplayFor(i => i.Company.PostalCode) @Html.DisplayFor(i => i.Company.City)</p>
      <p class="m-0">@Html.DisplayFor(i => i.Company.VATNumber)</p>
      <a class="stretched-link" href="/Companies/Details/@Model.Company.ID"></a>
    </div>
  </div>
  <div class="col-2 my-auto" align="center">
    <i class="fas fa-long-arrow-alt-right fa-4x" style="color:#007bff"></i>
  </div>
  <div class="col-5">
    <div class="card p-4">
      <h2>@Html.DisplayFor(i => i.Client.Firstname) @Html.DisplayFor(i => i.Client.Lastname)</h2>
      <p class="m-0">@Html.DisplayFor(i => i.Client.Street)</p>
      <p class="m-0">@Html.DisplayFor(i => i.Client.PostalCode) @Html.DisplayFor(i => i.Client.City)</p>
      <p class="m-0">@Html.DisplayFor(i => i.Client.Email)</p>
      <a class="stretched-link" href="/Clients/Details/@Model.Client.ID"></a>
    </div>
  </div>
</div>

<table class="table ">
  <thead>
    <tr>
      <th>Omschrijving</th>
      <th>Aantal</th>
      <th>Stukprijs</th>
      <th>Korting</th>
      <th>Subtotaal</th>
      <th>BTW</th>
    </tr>
  </thead>
  <tbody>
    @foreach (var item in Model.InvoiceLines)
    {
      <tr>

        <td>@Html.DisplayFor(modelItem => item.Description)</td>
        <td>@Html.DisplayFor(modelItem => item.Amount)</td>
        <td>€&nbsp;@Html.DisplayFor(modelItem => item.Price)</td>
        <td>@Html.DisplayFor(modelItem => item.DiscountPercent)&nbsp;%</td>
        <td>€&nbsp;@Html.DisplayFor(modelItem => item.TotalCostAfterDiscount)</td>
        <td>@Html.DisplayFor(modelItem => item.VAT)%</td>
      </tr>
    }
  </tbody>
  <tfoot style="border-top:2px solid #007bff">
    <tr>
      <td colspan="1"></td>
      <td colspan="3">Totaal excl. BTW</td>
      <td colspan="2">€&nbsp;@Model.TotalBeforeVAT</td>
    </tr>
    @foreach (var item in Model.TotalPerVATRate)
    {
      <tr>
        <td colspan="1"></td>
        <td colspan="3">@item.VATRate% over €&nbsp;@item.TotalBeforeVAT</td>
        <td colspan="2">
          €&nbsp;@item.VATPrice
        </td>
      </tr>

    }
    <tr style="border-top:2px solid #007bff">
      <td colspan="1"></td>
      <td colspan="3"><strong>Totaal incl. BTW</strong></td>
      <td colspan="2"><strong style="color:#007bff">€&nbsp;@Model.TotalAfterVAT</strong></td>
    </tr>
  </tfoot>
</table>

<div class="modal" id="deleteModel" tabindex="-1" role="dialog">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">Opgelet</h5>
        <button type="button" class="close" data-dismiss="modal">
          <span>&times;</span>
        </button>
      </div>
      @using (Html.BeginForm("Delete", "Invoices", FormMethod.Post))
      {
        <div class="modal-body">
          Weet u zeker dat u deze factuur wilt verwijderen?
          @if (Model.InvoiceLines.Count > 0)
          {
            <p>Geef hieronder ook een reden waarom u deze factuur wilt verwijderen</p>
            @Html.EditorFor(model => model.DeleteMessage, new { htmlAttributes = new { @class = "form-control" } })
          }
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Terug</button>


          @Html.AntiForgeryToken()
          @Html.HiddenFor(model => model.ID)

          <div class="form-actions no-color">
            <input type="submit" value="Verwijderen" class="btn btn-danger" />
          </div>
        </div>
      }
    </div>
  </div>
</div>

Bill.Web.UI/Views/Invoices/Edit.cshtml
@model Bill.Web.UI.ViewModels.InvoiceClientsCompanies

@{
  ViewBag.Title = $"Edit {@Model.Invoice.Code}";
}

<h2>Factuur <strong>@Model.Invoice.Code</strong> Aanpassen</h2>


@using (Html.BeginForm())
{
  @Html.AntiForgeryToken()

<div class="form-horizontal">
  <hr />
  @Html.ValidationSummary(true, "", new { @class = "text-danger" })
  @Html.HiddenFor(model => model.Invoice.ID)

  <div class="form-group">
    <div class="col-md-10">
      @Html.EditorFor(model => model.Invoice.Date, new { htmlAttributes = new { @class = "form-control" } })
      @Html.ValidationMessageFor(model => model.Invoice.Date, "", new { @class = "text-danger" })
    </div>
  </div>

  <div class="form-group">
    <div class="col-md-6">
      @Html.DropDownListFor(m => m.Invoice.ClientID, new SelectList(Model.Clients, "ID", "Email"), "Selecteer klant", new { @class = "form-control" })
    </div>
  </div>

  <div class="form-group">
    <div class="col-md-6">
      @Html.DropDownListFor(m => m.Invoice.CompanyID, new SelectList(Model.Companies, "ID", "Name"), "Selecteer bedrijf", new { @class = "form-control" })
    </div>
  </div>

  <div class="form-group">
    <div class="col-md-offset-2 col-md-10">
      <input type="submit" value="Save" class="btn btn-default" />
    </div>
  </div>
</div>
}

<div>
  @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
  @Scripts.Render("~/bundles/jqueryval")
}

Bill.Web.UI/Views/Invoices/Index.cshtml
@model IEnumerable<Bill.DataModels.Invoice>

@{
  ViewBag.Title = "Index";
}

<div class="row my-2">
  <h2>Facturen</h2>
  <div class="ml-4 my-auto">
    @using (Html.BeginForm("Index", "invoices", FormMethod.Get))
    {
      <div class="input-group">
        @Html.TextBox("SearchString", ViewBag.CurrentFilter as string, new { @class = "form-control", @placeholder = "Zoek factuur..." })
        <div class="input-group-append">
          <button class="btn btn-primary" type="submit" id="button-addon2"><i class="fas fa-search"></i></button>
        </div>
      </div>
    }
  </div>
  <div class="ml-auto my-auto">
    <a href="invoices/create" class="btn btn-primary">
      <i class="fas fa-plus"></i>
      Nieuwe Factuur
    </a>
  </div>
</div>
<table class="table">
  <tr>
    <th>Code</th>
    <th>@Html.ActionLink("Factuurdatum", "Index", new { sortOrder = ViewBag.DateSortParam, currentFilter = ViewBag.CurrentFilter })</th>
    <th>@Html.ActionLink("Voor klant", "Index", new { sortOrder = ViewBag.EmailSortParam, currentFilter = ViewBag.CurrentFilter })</th>
    <th>@Html.ActionLink("Bedrijf", "Index", new { sortOrder = ViewBag.CompanySortParam, currentFilter = ViewBag.CurrentFilter })</th>
    <th>@Html.ActionLink("Status", "Index", new { sortOrder = ViewBag.FinishedSortParam, currentFilter = ViewBag.CurrentFilter })</th>
    <th></th>
  </tr>

  @foreach (var item in Model)
  {
    <tr>
      <td>
        @Html.DisplayFor(modelItem => item.FormattedCode)
      </td>
      <td>
        @Html.DisplayFor(modelItem => item.Date)
      </td>
      <td>
        @Html.DisplayFor(modelItem => item.Client.Email)
      </td>
      <td>
        @Html.DisplayFor(modelItem => item.Company.Name)
      </td>
      <td>
        @if (item.Finished)
        {
          <span class="badge badge-success my-auto ml-2 p-2">Afgewerkt</span>
        }
        else
        {
          <span class="badge badge-secondary my-auto ml-2 p-2">Open</span>
        }
      </td>
      <td class="text-right">
        <a class="btn btn-sm btn-primary" href="@Url.Action("Details", "Invoices", new { id = item.ID})">Beheer factuur</a>
        <a class="btn btn-sm btn-primary" href="@Url.Action("Edit", "Invoices", new { id = item.ID})"><i class="fas fa-edit"></i></a>
        <a class="btn btn-sm btn-danger" href="@Url.Action("Delete", "Invoices", new { id = item.ID})"><i class="fas fa-trash"></i></a>
      </td>
    </tr>
  }
</table>